let DEBUG = true;
let GRAVITY = 10;

let SCREEN_WIDTH = 384;
let SCREEN_HEIGHT = 556;

let BALL_DIAMETER = 24;

//FLIPPERS
let FLIPPER_LENGTH = 48;
let FLIPPER_WIDTH = 18

let LEFT_FLIPPER_ROTATION_POINT_X = 111;
let LEFT_FLIPPER_ROTATION_POINT_Y = 515;

let RIGHT_FLIPPER_ROTATION_POINT_X = 209;
let RIGHT_FLIPPER_ROTATION_POINT_Y = 515;
