//META
let DEBUG = false;

//PHYSICS
let GRAVITY = 10;
let EPSILON = 0.1;

//SCREEN
let SCREEN_WIDTH = 384;
let SCREEN_HEIGHT = 556;

//BALL
let BALL_DIAMETER = 24;

let BONUS_SPAWN_BALL_X = 361;
let BONUS_SPAWN_BALL_Y = 245;

//FLIPPERS
let FLIPPER_LENGTH = 48;
let FLIPPER_WIDTH = 18

let LEFT_FLIPPER_ROTATION_POINT_X = 111;
let LEFT_FLIPPER_ROTATION_POINT_Y = 515;

let RIGHT_FLIPPER_ROTATION_POINT_X = 209;
let RIGHT_FLIPPER_ROTATION_POINT_Y = LEFT_FLIPPER_ROTATION_POINT_Y;

let BONUS_LEFT_FLIPPER_ROTATION_POINT_X = 139;
let BONUS_LEFT_FLIPPER_ROTATION_POINT_Y = 347 + 2; //TODO remove plus

let BONUS_RIGHT_FLIPPER_ROTATION_POINT_X = 237;
let BONUS_RIGHT_FLIPPER_ROTATION_POINT_Y = BONUS_LEFT_FLIPPER_ROTATION_POINT_Y;

let LEFT_FLIPPER_MIN_ROTATION = 35;
let RIGHT_FLIPPER_MIN_ROTATION = LEFT_FLIPPER_MIN_ROTATION * -1;
let LEFT_FLIPPER_MAX_ROTATION = -15;
let RIGHT_FLIPPER_MAX_ROTATION = LEFT_FLIPPER_MAX_ROTATION * -1;

let RIGHT_FLIPPER_ROTATION_SPEED = 15;
let LEFT_FLIPPER_ROTATION_SPEED = RIGHT_FLIPPER_ROTATION_SPEED * -1;

let LEFT_FLIPPER_KEY = 'a';
let RIGHT_FLIPPER_KEY = 'l';


//IMAGES
let BONUS_GHOST_BACKGROUND = 'assets/img/bonus-ghost/bonus_ghost_background.png';