const EVOLUTION_METHODS = {
    EXPERIENCE: "EX",
    THUNDER_STONE: "TS",
    WATER_STONE: "WS",
    FIRE_STONE: "FS",
    LEAF_STONE: "LS",
    MOON_STONE: "MS",
    LINK_CABLE: "LC"
}

const POKEDEX = {
    BULBASAUR:   { id: "001", name: "bulbasaur",   evolutionId: "002", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    IVYSAUR:     { id: "002", name: "ivysaur",     evolutionId: "003", basic: false , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    VENUSAUR:    { id: "003", name: "venusaur",    evolutionId: null,   basic: false, evolutionMethod: null },
    CHARMANDER:  { id: "004", name: "charmander",  evolutionId: "005", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    CHARMELEON:  { id: "005", name: "charmeleon",  evolutionId: "006", basic: false , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    CHARIZARD:   { id: "006", name: "charizard",   evolutionId: null,   basic: false, evolutionMethod: null },
    SQUIRTLE:    { id: "007", name: "squirtle",    evolutionId: "008", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    WARTORTLE:   { id: "008", name: "wartortle",   evolutionId: "009", basic: false , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    BLASTOISE:   { id: "009", name: "blastoise",   evolutionId: null,   basic: false, evolutionMethod: null },
    CATERPIE:    { id: "010", name: "caterpie",    evolutionId: "011", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    METAPOD:     { id: "011", name: "metapod",     evolutionId: "012", basic: false , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    BUTTERFREE:  { id: "012", name: "butterfree",  evolutionId: null,   basic: false, evolutionMethod: null },
    WEEDLE:      { id: "013", name: "weedle",      evolutionId: "014", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    KAKUNA:      { id: "014", name: "kakuna",      evolutionId: "015", basic: false , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    BEEDRILL:    { id: "015", name: "beedrill",    evolutionId: null,   basic: false, evolutionMethod: null },
    PIDGEY:      { id: "016", name: "pidgey",      evolutionId: "017", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    PIDGEOTTO:   { id: "017", name: "pidgeotto",   evolutionId: "018", basic: false , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    PIDGEOT:     { id: "018", name: "pidgeot",     evolutionId: null,   basic: false, evolutionMethod: null },
    RATTATA:     { id: "019", name: "rattata",     evolutionId: "020", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    RATICATE:    { id: "020", name: "raticate",    evolutionId: null,   basic: false, evolutionMethod: null },
    SPEAROW:     { id: "021", name: "spearow",     evolutionId: "022", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    FEAROW:      { id: "022", name: "fearow",      evolutionId: null,   basic: false, evolutionMethod: null },
    EKANS:       { id: "023", name: "ekans",       evolutionId: "024", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    ARBOK:       { id: "024", name: "arbok",       evolutionId: null,   basic: false, evolutionMethod: null },
    PIKACHU:     { id: "025", name: "pikachu",     evolutionId: "026", basic: true  , evolutionMethod: EVOLUTION_METHODS.THUNDER_STONE },
    RAICHU:      { id: "026", name: "raichu",      evolutionId: null,   basic: false, evolutionMethod: null },
    SANDSHREW:   { id: "027", name: "sandshrew",   evolutionId: "028", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    SANDSLASH:   { id: "028", name: "sandslash",   evolutionId: null,   basic: false, evolutionMethod: null },
    NIDORAN_F:   { id: "029", name: "nidoran_f",   evolutionId: "030", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    NIDORINA:    { id: "030", name: "nidorina",    evolutionId: "031", basic: false , evolutionMethod: EVOLUTION_METHODS.MOON_STONE },
    NIDOQUEEN:   { id: "031", name: "nidoqueen",   evolutionId: null,   basic: false, evolutionMethod: null },
    NIDORAN_M:   { id: "032", name: "nidoran_m",   evolutionId: "033", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    NIDORINO:    { id: "033", name: "nidorino",    evolutionId: "034", basic: false , evolutionMethod: EVOLUTION_METHODS.MOON_STONE },
    NIDOKING:    { id: "034", name: "nidoking",    evolutionId: null,   basic: false, evolutionMethod: null },
    CLEFAIRY:    { id: "035", name: "clefairy",    evolutionId: "036", basic: true  , evolutionMethod: EVOLUTION_METHODS.MOON_STONE },
    CLEFABLE:    { id: "036", name: "clefable",    evolutionId: null,   basic: false, evolutionMethod: null },
    VULPIX:      { id: "037", name: "vulpix",      evolutionId: "038", basic: true  , evolutionMethod: EVOLUTION_METHODS.FIRE_STONE },
    NINETALES:   { id: "038", name: "ninetales",   evolutionId: null,   basic: false, evolutionMethod: null },
    JIGGLYPUFF:  { id: "039", name: "jigglypuff",  evolutionId: "040", basic: true  , evolutionMethod: EVOLUTION_METHODS.MOON_STONE },
    WIGGLYTUFF:  { id: "040", name: "wigglytuff",  evolutionId: null,   basic: false, evolutionMethod: null },
    ZUBAT:       { id: "041", name: "zubat",       evolutionId: "042", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    GOLBAT:      { id: "042", name: "golbat",      evolutionId: null,   basic: false, evolutionMethod: null },
    ODDISH:      { id: "043", name: "oddish",      evolutionId: "044", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    GLOOM:       { id: "044", name: "gloom",       evolutionId: "045", basic: false , evolutionMethod: EVOLUTION_METHODS.LEAF_STONE },
    VILEPLUME:   { id: "045", name: "vileplume",   evolutionId: null,   basic: false, evolutionMethod: null },
    PARAS:       { id: "046", name: "paras",       evolutionId: "047", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    PARASECT:    { id: "047", name: "parasect",    evolutionId: null,   basic: false, evolutionMethod: null },
    VENONAT:     { id: "048", name: "venonat",     evolutionId: "049", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    VENOMOTH:    { id: "049", name: "venomoth",    evolutionId: null,   basic: false, evolutionMethod: null },
    DIGLETT:     { id: "050", name: "diglett",     evolutionId: "051", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    DUGTRIO:     { id: "051", name: "dugtrio",     evolutionId: null,   basic: false, evolutionMethod: null },
    MEOWTH:      { id: "052", name: "meowth",      evolutionId: "053", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    PERSIAN:     { id: "053", name: "persian",     evolutionId: null,   basic: false, evolutionMethod: null },
    PSYDUCK:     { id: "054", name: "psyduck",     evolutionId: "055", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    GOLDUCK:     { id: "055", name: "golduck",     evolutionId: null,   basic: false, evolutionMethod: null },
    MANKEY:      { id: "056", name: "mankey",      evolutionId: "057", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    PRIMEAPE:    { id: "057", name: "primeape",    evolutionId: null,   basic: false, evolutionMethod: null },
    GROWLITHE:   { id: "058", name: "growlithe",   evolutionId: "059", basic: true  , evolutionMethod: EVOLUTION_METHODS.FIRE_STONE },
    ARCANINE:    { id: "059", name: "arcanine",    evolutionId: null,   basic: false, evolutionMethod: null },
    POLIWAG:     { id: "060", name: "poliwag",     evolutionId: "061", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    POLIWHIRL:   { id: "061", name: "poliwhirl",   evolutionId: "062", basic: false , evolutionMethod: EVOLUTION_METHODS.WATER_STONE },
    POLIWRATH:   { id: "062", name: "poliwrath",   evolutionId: null,   basic: false, evolutionMethod: null },
    ABRA:        { id: "063", name: "abra",        evolutionId: "064", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    KADABRA:     { id: "064", name: "kadabra",     evolutionId: "065", basic: false , evolutionMethod: EVOLUTION_METHODS.LINK_CABLE },
    ALAKAZAM:    { id: "065", name: "alakazam",    evolutionId: null,   basic: false, evolutionMethod: null },
    MACHOP:      { id: "066", name: "machop",      evolutionId: "067", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    MACHOKE:     { id: "067", name: "machoke",     evolutionId: "068", basic: false , evolutionMethod: EVOLUTION_METHODS.LINK_CABLE },
    MACHAMP:     { id: "068", name: "machamp",     evolutionId: null,   basic: false, evolutionMethod: null },
    BELLSPROUT:  { id: "069", name: "bellsprout",  evolutionId: "070", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    WEEPINBELL:  { id: "070", name: "weepinbell",  evolutionId: "071", basic: false , evolutionMethod: EVOLUTION_METHODS.LEAF_STONE },
    VICTREEBEL:  { id: "071", name: "victreebel",  evolutionId: null,   basic: false, evolutionMethod: null },
    TENTACOOL:   { id: "072", name: "tentacool",   evolutionId: "073", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    TENTACRUEL:  { id: "073", name: "tentacruel",  evolutionId: null,   basic: false, evolutionMethod: null },
    GEODUDE:     { id: "074", name: "geodude",     evolutionId: "075", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    GRAVELER:    { id: "075", name: "graveler",    evolutionId: "076", basic: false , evolutionMethod: EVOLUTION_METHODS.LINK_CABLE },
    GOLEM:       { id: "076", name: "golem",       evolutionId: null,   basic: false, evolutionMethod: null },
    PONYTA:      { id: "077", name: "ponyta",      evolutionId: "078", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    RAPIDASH:    { id: "078", name: "rapidash",    evolutionId: null,   basic: false, evolutionMethod: null },
    SLOWPOKE:    { id: "079", name: "slowpoke",    evolutionId: "080", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    SLOWBRO:     { id: "080", name: "slowbro",     evolutionId: null,   basic: false, evolutionMethod: null },
    MAGNEMITE:   { id: "081", name: "magnemite",   evolutionId: "082", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    MAGNETON:    { id: "082", name: "magneton",    evolutionId: null,   basic: false, evolutionMethod: null },
    FARFETCHD:   { id: "083", name: "farfetchd",   evolutionId: null,   basic: true , evolutionMethod: null },
    DODUO:       { id: "084", name: "doduo",       evolutionId: "085", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    DODRIO:      { id: "085", name: "dodrio",      evolutionId: null,   basic: false, evolutionMethod: null },
    SEEL:        { id: "086", name: "seel",        evolutionId: "087", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    DEWGONG:     { id: "087", name: "dewgong",     evolutionId: null,   basic: false, evolutionMethod: null },
    GRIMER:      { id: "088", name: "grimer",      evolutionId: "089", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    MUK:         { id: "089", name: "muk",         evolutionId: null,   basic: false, evolutionMethod: null },
    SHELLDER:    { id: "090", name: "shellder",    evolutionId: "091", basic: true  , evolutionMethod: EVOLUTION_METHODS.WATER_STONE },
    CLOYSTER:    { id: "091", name: "cloyster",    evolutionId: null,   basic: false, evolutionMethod: null },
    GASTLY:      { id: "092", name: "gastly",      evolutionId: "093", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    HAUNTER:     { id: "093", name: "haunter",     evolutionId: "094", basic: false , evolutionMethod: EVOLUTION_METHODS.LINK_CABLE },
    GENGAR:      { id: "094", name: "gengar",      evolutionId: null,   basic: false, evolutionMethod: null },
    ONIX:        { id: "095", name: "onix",        evolutionId: null,   basic: true , evolutionMethod: null },
    DROWZEE:     { id: "096", name: "drowzee",     evolutionId: "097", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    HYPNO:       { id: "097", name: "hypno",       evolutionId: null,   basic: false, evolutionMethod: null },
    KRABBY:      { id: "098", name: "krabby",      evolutionId: "099", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    KINGLER:     { id: "099", name: "kingler",     evolutionId: null,   basic: false, evolutionMethod: null },
    VOLTORB:     { id: "100", name: "voltorb",     evolutionId: "101", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    ELECTRODE:   { id: "101", name: "electrode",   evolutionId: null,   basic: false, evolutionMethod: null },
    EXEGGCUTE:   { id: "102", name: "exeggcute",   evolutionId: "103", basic: true  , evolutionMethod: EVOLUTION_METHODS.LEAF_STONE },
    EXEGGUTOR:   { id: "103", name: "exeggutor",   evolutionId: null,   basic: false, evolutionMethod: null },
    CUBONE:      { id: "104", name: "cubone",      evolutionId: "105", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    MAROWAK:     { id: "105", name: "marowak",     evolutionId: null,   basic: false, evolutionMethod: null },
    HITMONLEE:   { id: "106", name: "hitmonlee",   evolutionId: null,   basic: true , evolutionMethod: null },
    HITMONCHAN:  { id: "107", name: "hitmonchan",  evolutionId: null,   basic: true , evolutionMethod: null },
    LICKITUNG:   { id: "108", name: "lickitung",   evolutionId: null,   basic: true , evolutionMethod: null },
    KOFFING:     { id: "109", name: "koffing",     evolutionId: "110", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    WEEZING:     { id: "110", name: "weezing",     evolutionId: null,   basic: false, evolutionMethod: null },
    RHYHORN:     { id: "111", name: "rhyhorn",     evolutionId: "112", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    RHYDON:      { id: "112", name: "rhydon",      evolutionId: null,   basic: false, evolutionMethod: null },
    CHANSEY:     { id: "113", name: "chansey",     evolutionId: null,   basic: true , evolutionMethod: null },
    TANGELA:     { id: "114", name: "tangela",     evolutionId: null,   basic: true , evolutionMethod: null },
    KANGASKHAN:  { id: "115", name: "kangaskhan",  evolutionId: null,   basic: true , evolutionMethod: null },
    HORSEA:      { id: "116", name: "horsea",      evolutionId: "117", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    SEADRA:      { id: "117", name: "seadra",      evolutionId: null,   basic: false, evolutionMethod: null },
    GOLDEEN:     { id: "118", name: "goldeen",     evolutionId: "119", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    SEAKING:     { id: "119", name: "seaking",     evolutionId: null,   basic: false, evolutionMethod: null },
    STARYU:      { id: "120", name: "staryu",      evolutionId: "121", basic: true  , evolutionMethod: EVOLUTION_METHODS.WATER_STONE },
    STARMIE:     { id: "121", name: "starmie",     evolutionId: null,   basic: false, evolutionMethod: null },
    MR_MIME:     { id: "122", name: "mr_mime",     evolutionId: null,   basic: true , evolutionMethod: null },
    SCYTHER:     { id: "123", name: "scyther",     evolutionId: null,   basic: true , evolutionMethod: null },
    JYNX:        { id: "124", name: "jynx",        evolutionId: null,   basic: true , evolutionMethod: null },
    ELECTABUZZ:  { id: "125", name: "electabuzz",  evolutionId: null,   basic: true , evolutionMethod: null },
    MAGMAR:      { id: "126", name: "magmar",      evolutionId: null,   basic: true , evolutionMethod: null },
    PINSIR:      { id: "127", name: "pinsir",      evolutionId: null,   basic: true , evolutionMethod: null },
    TAUROS:      { id: "128", name: "tauros",      evolutionId: null,   basic: true , evolutionMethod: null },
    MAGIKARP:    { id: "129", name: "magikarp",    evolutionId: "130", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    GYARADOS:    { id: "130", name: "gyarados",    evolutionId: null,   basic: false, evolutionMethod: null },
    LAPRAS:      { id: "131", name: "lapras",      evolutionId: null,   basic: true , evolutionMethod: null },
    DITTO:       { id: "132", name: "ditto",       evolutionId: null,   basic: true , evolutionMethod: null },
    EEVEE:       { id: "133", name: "eevee",       evolutionId: null,   basic: true , evolutionMethod: null }, // evoluciones por piedra (WS/TS/FS) gestionadas fuera
    VAPOREON:    { id: "134", name: "vaporeon",    evolutionId: null,   basic: false, evolutionMethod: null },
    JOLTEON:     { id: "135", name: "jolteon",     evolutionId: null,   basic: false, evolutionMethod: null },
    FLAREON:     { id: "136", name: "flareon",     evolutionId: null,   basic: false, evolutionMethod: null },
    PORYGON:     { id: "137", name: "porygon",     evolutionId: null,   basic: true , evolutionMethod: null },
    OMANYTE:     { id: "138", name: "omanyte",     evolutionId: "139", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    OMASTAR:     { id: "139", name: "omastar",     evolutionId: null,   basic: false, evolutionMethod: null },
    KABUTO:      { id: "140", name: "kabuto",      evolutionId: "141", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    KABUTOPS:    { id: "141", name: "kabutops",    evolutionId: null,   basic: false, evolutionMethod: null },
    AERODACTYL:  { id: "142", name: "aerodactyl",  evolutionId: null,   basic: true , evolutionMethod: null },
    SNORLAX:     { id: "143", name: "snorlax",     evolutionId: null,   basic: true , evolutionMethod: null },
    ARTICUNO:    { id: "144", name: "articuno",    evolutionId: null,   basic: true , evolutionMethod: null },
    ZAPDOS:      { id: "145", name: "zapdos",      evolutionId: null,   basic: true , evolutionMethod: null },
    MOLTRES:     { id: "146", name: "moltres",     evolutionId: null,   basic: true , evolutionMethod: null },
    DRATINI:     { id: "147", name: "dratini",     evolutionId: "148", basic: true  , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    DRAGONAIR:   { id: "148", name: "dragonair",   evolutionId: "149", basic: false , evolutionMethod: EVOLUTION_METHODS.EXPERIENCE },
    DRAGONITE:   { id: "149", name: "dragonite",   evolutionId: null,   basic: false, evolutionMethod: null },
    MEWTWO:      { id: "150", name: "mewtwo",      evolutionId: null,   basic: true , evolutionMethod: null },
    MEW:         { id: "151", name: "mew",         evolutionId: null,   basic: true , evolutionMethod: null }
};

const BASIC_POKEMON = Object.values(POKEDEX).filter(pokemon => pokemon.basic);
const ALL_POKEMON = Object.values(POKEDEX);

function getPokemonById(id) {
    const key = String(id).padStart(3, '0');
    return Object.values(POKEDEX).find(p => p.id === key) || null;
}

function canEvolve(id){
    const currentPokemon = getPokemonById(id);
    return !!(currentPokemon && currentPokemon.evolutionId);
}